"""Shared records and protocols for Economic World Models."""

from ewm._internal.imports import register_module_aliases

from .assurance.coherence import (
    CoherenceRelation,
    CoherenceReport,
    HardCoherenceCondition,
    HardCoherenceResult,
    SoftCoherenceDiagnostic,
    SoftCoherenceResult,
    evaluate_coherence,
)
from .assurance.evaluation import (
    EvaluationLayerReport,
    EvaluationReport,
    LayeredEvaluationReport,
    MeasurementStatus,
    MetricMeasurement,
    evaluate_event_log,
)
from .assurance.reconciliation import (
    FunctionalStateReconciler,
    ReconciliationRule,
    StateFeasibilityRule,
)
from .domain.agents import FunctionalAgent
from .domain.constraints import ConstraintSet, FunctionalConstraint
from .domain.definition import (
    AgentBlock,
    CoherenceCondition,
    CoherenceKind,
    EconomicWorldModelDefinition,
    InterventionSemantics,
    KernelDefinition,
    SpaceDefinition,
    WorldComponent,
)
from .domain.mechanisms import FunctionalMechanism
from .domain.protocols import (
    AgentPolicy,
    AlignmentReportRecord,
    Constraint,
    DDGEProblem,
    EconomicWorld,
    EquilibriumProblem,
    ExternalEvidenceRecord,
    InstitutionalEvolution,
    InstitutionChangeProposal,
    InstitutionChangeReport,
    InstitutionManifestRecord,
    Mechanism,
    RealWorldAlignment,
    StateReconciler,
)
from .domain.records import (
    Action,
    CoevolutionProposal,
    CoevolutionReport,
    CoevolutionSnapshot,
    CoevolutionUpdate,
    ConsistencyCheck,
    ConstraintViolation,
    DDGECandidate,
    DDGEConsistencyCertificate,
    DDGEResult,
    EquilibriumResult,
    ExperimentResult,
    FixedPoint,
    GeneratedDataset,
    RunMetadata,
    Transition,
)
from .domain.specs import (
    AgentSpecification,
    AlignmentSpecification,
    CoevolutionSpecification,
    ConstraintsSpecification,
    CorrectionSpecification,
    DataSourcesSpecification,
    EnvironmentSpecification,
    EvaluationSpecification,
    MechanismSpecification,
    SchedulerSpecification,
    StateSpecification,
    UpdateSpecification,
    WorldSpecification,
)
from .provenance.contracts import (
    RuntimeContract,
    SchedulerPolicy,
    ViolationPolicy,
    runtime_contract_digest,
)
from .provenance.randomness import make_rng, spawn_rngs
from .provenance.replay import (
    REPLAY_SCHEMA_VERSION,
    ReplayBundle,
    ReplayManifest,
    ReplayReport,
    export_replay,
    replay_bundle_from_events,
    replay_world,
)
from .provenance.serialization import (
    CANONICAL_STATE_CODEC_ID,
    CanonicalStateCodec,
    StateCodec,
    canonical_json,
    content_digest,
    state_digest,
)
from .runtime.dynamics.coevolution import ControlledCoevolution, ProposalRule
from .runtime.dynamics.interventions import (
    InterventionApplication,
    InterventionDiff,
    InterventionOperation,
    InterventionRecord,
    InterventionTarget,
    SetValueIntervention,
    apply_intervention,
)
from .runtime.execution.compiler import (
    AgentFactory,
    InitialStateFactory,
    MechanismFactory,
    MechanismKey,
    ObservationFactory,
    RuntimeAdapter,
    RuntimeAdapterRegistry,
    WorldBindings,
    compile_world,
    mechanism_key,
)
from .runtime.execution.kernels import (
    CallableStochasticKernel,
    CategoricalKernel,
    KernelDraw,
    RNGProvenance,
)
from .runtime.execution.world import ProvenanceMode, World
from .runtime.records.events import (
    EVENT_GENESIS_HASH,
    EVENT_SCHEMA_VERSION,
    Event,
    EventLog,
    EventLogView,
    verify_event_chain,
)
from .runtime.records.updates import convex_update

register_module_aliases(
    f"{__name__}.runtime",
    {
        "coevolution": "dynamics.coevolution",
        "events": "records.events",
        "interventions": "dynamics.interventions",
        "kernels": "execution.kernels",
        "updates": "records.updates",
        "world": "execution.world",
        "compiler": "execution.compiler",
    },
    preserve_symbol_modules=False,
)

register_module_aliases(
    __name__,
    {
        "agents": "domain.agents",
        "coevolution": "runtime.dynamics.coevolution",
        "coherence": "assurance.coherence",
        "compiler": "runtime.execution.compiler",
        "constraints": "domain.constraints",
        "contracts": "provenance.contracts",
        "definition": "domain.definition",
        "evaluation": "assurance.evaluation",
        "events": "runtime.records.events",
        "evidence": "assurance.evidence",
        "interventions": "runtime.dynamics.interventions",
        "kernels": "runtime.execution.kernels",
        "mechanisms": "domain.mechanisms",
        "protocols": "domain.protocols",
        "randomness": "provenance.randomness",
        "reconciliation": "assurance.reconciliation",
        "records": "domain.records",
        "replay": "provenance.replay",
        "serialization": "provenance.serialization",
        "specs": "domain.specs",
        "updates": "runtime.records.updates",
        "world": "runtime.execution.world",
    },
)

__all__ = [
    "CANONICAL_STATE_CODEC_ID",
    "EVENT_GENESIS_HASH",
    "EVENT_SCHEMA_VERSION",
    "REPLAY_SCHEMA_VERSION",
    "Action",
    "AgentBlock",
    "AgentFactory",
    "AgentPolicy",
    "AgentSpecification",
    "AlignmentReportRecord",
    "AlignmentSpecification",
    "CallableStochasticKernel",
    "CanonicalStateCodec",
    "CategoricalKernel",
    "CoevolutionProposal",
    "CoevolutionReport",
    "CoevolutionSnapshot",
    "CoevolutionSpecification",
    "CoevolutionUpdate",
    "CoherenceCondition",
    "CoherenceKind",
    "CoherenceRelation",
    "CoherenceReport",
    "ConsistencyCheck",
    "Constraint",
    "ConstraintSet",
    "ConstraintViolation",
    "ConstraintsSpecification",
    "ControlledCoevolution",
    "CorrectionSpecification",
    "DDGECandidate",
    "DDGEConsistencyCertificate",
    "DDGEProblem",
    "DDGEResult",
    "DataSourcesSpecification",
    "EconomicWorld",
    "EconomicWorldModelDefinition",
    "EnvironmentSpecification",
    "EquilibriumProblem",
    "EquilibriumResult",
    "EvaluationLayerReport",
    "EvaluationReport",
    "EvaluationSpecification",
    "Event",
    "EventLog",
    "EventLogView",
    "ExperimentResult",
    "ExternalEvidenceRecord",
    "FixedPoint",
    "FunctionalAgent",
    "FunctionalConstraint",
    "FunctionalMechanism",
    "FunctionalStateReconciler",
    "GeneratedDataset",
    "HardCoherenceCondition",
    "HardCoherenceResult",
    "InitialStateFactory",
    "InstitutionChangeProposal",
    "InstitutionChangeReport",
    "InstitutionManifestRecord",
    "InstitutionalEvolution",
    "InterventionApplication",
    "InterventionDiff",
    "InterventionOperation",
    "InterventionRecord",
    "InterventionSemantics",
    "InterventionTarget",
    "KernelDefinition",
    "KernelDraw",
    "LayeredEvaluationReport",
    "MeasurementStatus",
    "Mechanism",
    "MechanismFactory",
    "MechanismKey",
    "MechanismSpecification",
    "MetricMeasurement",
    "ObservationFactory",
    "ProposalRule",
    "ProvenanceMode",
    "RNGProvenance",
    "RealWorldAlignment",
    "ReconciliationRule",
    "ReplayBundle",
    "ReplayManifest",
    "ReplayReport",
    "RunMetadata",
    "RuntimeAdapter",
    "RuntimeAdapterRegistry",
    "RuntimeContract",
    "SchedulerPolicy",
    "SchedulerSpecification",
    "SetValueIntervention",
    "SoftCoherenceDiagnostic",
    "SoftCoherenceResult",
    "SpaceDefinition",
    "StateCodec",
    "StateFeasibilityRule",
    "StateReconciler",
    "StateSpecification",
    "Transition",
    "UpdateSpecification",
    "ViolationPolicy",
    "World",
    "WorldBindings",
    "WorldComponent",
    "WorldSpecification",
    "apply_intervention",
    "canonical_json",
    "compile_world",
    "content_digest",
    "convex_update",
    "evaluate_coherence",
    "evaluate_event_log",
    "export_replay",
    "make_rng",
    "mechanism_key",
    "replay_bundle_from_events",
    "replay_world",
    "runtime_contract_digest",
    "spawn_rngs",
    "state_digest",
    "verify_event_chain",
]
