"""Optional capability substrates layered above the deterministic EWM core."""

from ewm._internal.imports import register_module_aliases

from .assessment.levels import (
    LEVEL_REQUIREMENTS,
    AxisAssessment,
    AxisEvidence,
    AxisStatus,
    CapabilityAssessment,
    CapabilityEvidence,
    CapabilityLevel,
    EvidenceKind,
    LevelRequirement,
    RequirementGate,
    ValidatedCapabilityEvidence,
    assess_capability,
    assess_validated_capability,
    documented_prototype_evidence,
    requirement_gate,
)
from .engineering.alignment import (
    AbsoluteErrorMetric,
    AlignmentContext,
    AlignmentMetric,
    AlignmentProvenance,
    AlignmentReport,
    AlignmentRestoreReport,
    AlignmentSnapshot,
    AppliedCorrection,
    BoundedAlignment,
    CorrectionPlanner,
    CorrectionProposal,
    ExternalDataAdapter,
    ExternalObservation,
    FunctionalCorrectionPlanner,
)
from .engineering.cognition import (
    ActionSchema,
    CognitiveActionError,
    CognitiveAgent,
    CognitiveDecision,
    CognitiveTool,
    DecisionProvenance,
    FunctionalCognitiveTool,
    LanguageModelBackend,
    MemoryEntry,
    ModelRequest,
    ModelResponse,
)
from .engineering.evolution import (
    EVOLUTION_SCHEMA_VERSION,
    CapabilityKind,
    CapabilityManifest,
    EvolutionProposal,
    EvolutionRegistry,
    GateEvidence,
    PromotionPolicy,
    PromotionReport,
    RollbackReport,
)
from .engineering.institutions import (
    GovernedInstitutions,
    InstitutionCheck,
    InstitutionKind,
    InstitutionManifest,
    InstitutionPolicy,
    InstitutionProposal,
    InstitutionSnapshot,
    InstitutionTransitionReport,
    InstitutionValidator,
)

register_module_aliases(
    __name__,
    {
        "alignment": "engineering.alignment",
        "cognition": "engineering.cognition",
        "evolution": "engineering.evolution",
        "institutions": "engineering.institutions",
        "levels": "assessment.levels",
        "readiness": "assessment.readiness",
    },
)

__all__ = [
    "EVOLUTION_SCHEMA_VERSION",
    "LEVEL_REQUIREMENTS",
    "AbsoluteErrorMetric",
    "ActionSchema",
    "AlignmentContext",
    "AlignmentMetric",
    "AlignmentProvenance",
    "AlignmentReport",
    "AlignmentRestoreReport",
    "AlignmentSnapshot",
    "AppliedCorrection",
    "AxisAssessment",
    "AxisEvidence",
    "AxisStatus",
    "BoundedAlignment",
    "CapabilityAssessment",
    "CapabilityEvidence",
    "CapabilityKind",
    "CapabilityLevel",
    "CapabilityManifest",
    "CognitiveActionError",
    "CognitiveAgent",
    "CognitiveDecision",
    "CognitiveTool",
    "CorrectionPlanner",
    "CorrectionProposal",
    "DecisionProvenance",
    "EvidenceKind",
    "EvolutionProposal",
    "EvolutionRegistry",
    "ExternalDataAdapter",
    "ExternalObservation",
    "FunctionalCognitiveTool",
    "FunctionalCorrectionPlanner",
    "GateEvidence",
    "GovernedInstitutions",
    "InstitutionCheck",
    "InstitutionKind",
    "InstitutionManifest",
    "InstitutionPolicy",
    "InstitutionProposal",
    "InstitutionSnapshot",
    "InstitutionTransitionReport",
    "InstitutionValidator",
    "LanguageModelBackend",
    "LevelRequirement",
    "MemoryEntry",
    "ModelRequest",
    "ModelResponse",
    "PromotionPolicy",
    "PromotionReport",
    "RequirementGate",
    "RollbackReport",
    "ValidatedCapabilityEvidence",
    "assess_capability",
    "assess_validated_capability",
    "documented_prototype_evidence",
    "requirement_gate",
]
